#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.34011
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
using System.IO;
using System.IO.IsolatedStorage;
using Microsoft.Phone.Data.Linq.Mapping;
using Microsoft.Phone.Data.Linq;


public class DebugWriter : TextWriter
{
    private const int DefaultBufferSize = 256;
    private System.Text.StringBuilder _buffer;

    public DebugWriter()
    {
        BufferSize = 256;
        _buffer = new System.Text.StringBuilder(BufferSize);
    }

    public int BufferSize
    {
        get;
        private set;
    }

    public override System.Text.Encoding Encoding
    {
        get { return System.Text.Encoding.UTF8; }
    }

    #region StreamWriter Overrides
    public override void Write(char value)
    {
        _buffer.Append(value);
        if (_buffer.Length >= BufferSize)
            Flush();
    }

    public override void WriteLine(string value)
    {
        Flush();

        using(var reader = new StringReader(value))
        {
            string line; 
            while( null != (line = reader.ReadLine()))
                System.Diagnostics.Debug.WriteLine(line);
        }
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            Flush();
    }

    public override void Flush()
    {
        if (_buffer.Length > 0)
        {
            System.Diagnostics.Debug.WriteLine(_buffer);
            _buffer.Clear();
        }
    }
    #endregion
}


	public partial class ImieninyContext : System.Data.Linq.DataContext
	{
		
		public bool CreateIfNotExists()
		{
			bool created = false;
			if (!this.DatabaseExists())
			{
				string[] names = this.GetType().Assembly.GetManifestResourceNames();
				string name = names.Where(n => n.EndsWith(FileName)).FirstOrDefault();
				if (name != null)
				{
					using (Stream resourceStream = Assembly.GetExecutingAssembly().GetManifestResourceStream(name))
					{
						if (resourceStream != null)
						{
							using (IsolatedStorageFile myIsolatedStorage = IsolatedStorageFile.GetUserStoreForApplication())
							{
								using (IsolatedStorageFileStream fileStream = new IsolatedStorageFileStream(FileName, FileMode.Create, myIsolatedStorage))
								{
									using (BinaryWriter writer = new BinaryWriter(fileStream))
									{
										long length = resourceStream.Length;
										byte[] buffer = new byte[32];
										int readCount = 0;
										using (BinaryReader reader = new BinaryReader(resourceStream))
										{
											// read file in chunks in order to reduce memory consumption and increase performance
											while (readCount < length)
											{
												int actual = reader.Read(buffer, 0, buffer.Length);
												readCount += actual;
												writer.Write(buffer, 0, actual);
											}
										}
									}
								}
							}
							created = true;
						}
						else
						{
							this.CreateDatabase();
							created = true;
						}
					}
				}
				else
				{
					this.CreateDatabase();
					created = true;
				}
			}
			return created;
		}
		
		public bool LogDebug
		{
			set
			{
				if (value)
				{
					this.Log = new DebugWriter();
				}
			}
		}
		
		public static string ConnectionString = "Data Source=isostore:/Imieniny.sdf";

		public static string ConnectionStringReadOnly = "Data Source=appdata:/Imieniny.sdf;File Mode=Read Only;";

		public static string FileName = "Imieniny.sdf";

		public ImieninyContext(string connectionString) : base(connectionString)
		{
			OnCreated();
		}
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTabela(Tabela instance);
    partial void UpdateTabela(Tabela instance);
    partial void DeleteTabela(Tabela instance);
    #endregion
		
		public System.Data.Linq.Table<Tabela> Tabela
		{
			get
			{
				return this.GetTable<Tabela>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="tabela")]
	public partial class Tabela : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Miesiac;
		
		private int _Dzien;
		
		private string _Imieniny;
		
		private string _Znajomy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMiesiacChanging(int value);
    partial void OnMiesiacChanged();
    partial void OnDzienChanging(int value);
    partial void OnDzienChanged();
    partial void OnImieninyChanging(string value);
    partial void OnImieninyChanged();
    partial void OnZnajomyChanging(string value);
    partial void OnZnajomyChanged();
    #endregion
		
		public Tabela()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="miesiac", Storage="_Miesiac", DbType="Int NOT NULL")]
		public int Miesiac
		{
			get
			{
				return this._Miesiac;
			}
			set
			{
				if ((this._Miesiac != value))
				{
					this.OnMiesiacChanging(value);
					this.SendPropertyChanging();
					this._Miesiac = value;
					this.SendPropertyChanged("Miesiac");
					this.OnMiesiacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="dzien", Storage="_Dzien", DbType="Int NOT NULL")]
		public int Dzien
		{
			get
			{
				return this._Dzien;
			}
			set
			{
				if ((this._Dzien != value))
				{
					this.OnDzienChanging(value);
					this.SendPropertyChanging();
					this._Dzien = value;
					this.SendPropertyChanged("Dzien");
					this.OnDzienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="imieniny", Storage="_Imieniny", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Imieniny
		{
			get
			{
				return this._Imieniny;
			}
			set
			{
				if ((this._Imieniny != value))
				{
					this.OnImieninyChanging(value);
					this.SendPropertyChanging();
					this._Imieniny = value;
					this.SendPropertyChanged("Imieniny");
					this.OnImieninyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="znajomy", Storage="_Znajomy", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Znajomy
		{
			get
			{
				return this._Znajomy;
			}
			set
			{
				if ((this._Znajomy != value))
				{
					this.OnZnajomyChanging(value);
					this.SendPropertyChanging();
					this._Znajomy = value;
					this.SendPropertyChanged("Znajomy");
					this.OnZnajomyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
